#!/usr/bin/env python3
"""Rebuild lib/lpv_blocks.glsl as a pure function, with no storage image.

Why
---
`imgBlockData` is declared as a 1D storage image, and 1D is not one of the
sampler shapes this engine binds, so the compute pass that uses it fails to
compile:

    compute world0/shadowcomp SPIR-V failed: ShaderCompileException:
    Unsupported texture dimensions '1D' for sampler imgBlockData

That kills the whole light-propagation volume: coloured candles, per-block light
colour, and the glass tint that makes a blue filter tint the light behind it. The
buffer is also written by `setup.csh`, which this engine skips outright - "no
stage exists for them yet" - so even a 2D version would be written by nothing.

The data in it does not need a buffer. Every entry is a compile-time constant
selected by the block id: `lightColor = vec3(0.839, 0.541, 0.2)`, a range, a tint
and a mask. So it can be a function.

This script performs the extraction mechanically, because transcribing a thousand
lines of table by hand is exactly how a colour constant gets dropped, and a
dropped constant is a torch that lights the room the wrong colour with nothing to
say so.

What it does:
  * takes the helper block and the id table verbatim out of dimensions/setup.csh
  * wraps them in `uvec2 ptBlockLightData(int blockId)`, returning the same two
    packed uints the image held
  * writes lib/lpv_blocks.glsl, whose previous contents were two uimage1D
    declarations that no longer exist

Run from the pack root. Idempotent: it always reads setup.csh, never its own
output.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS = os.path.join(ROOT, "shaders")
SETUP = os.path.join(SHADERS, "dimensions", "setup.csh")
OUT = os.path.join(SHADERS, "lib", "lpv_blocks.glsl")

HEADER = '''// FauxTracer - per-block light and tint data
// ---------------------------------------------------------------------------
// Generated by tools/port_lpv_table.py out of dimensions/setup.csh. Edit the
// table there and re-run it, or edit both - but the point of generating it is
// that the table is the same table, not a hand-copied approximation of it.
//
// This used to be a storage image.
//
//   layout(rg32ui) uniform writeonly uimage1D imgBlockData;
//
// 1D is not one of the sampler shapes this engine binds - the bindable set is
// 2D, 2DShadow, 2DArray, 2DArrayShadow, 2DMS, 2DMSArray, Cube, CubeShadow,
// CubeArray, CubeArrayShadow, with any i/u prefix stripped - so the compute pass
// that used it would not compile at all:
//
//   compute world0/shadowcomp SPIR-V failed: Unsupported texture dimensions
//   '1D' for sampler imgBlockData
//
// Making it a 2D image would fix the compile and nothing else, because the pass
// that populated it, setup.csh, is skipped by the engine outright ("compute
// programs skipped, no stage exists for them yet"). The buffer would be written
// by nothing and read as whatever was in it.
//
// It does not need to be a buffer. Every entry is a compile-time constant picked
// by block id - a light colour, a range, a tint and a mask - so a function of the
// id computes the identical value, with no binding, no format and no pass.
//
// The cost is that the chain of comparisons is evaluated per call rather than
// read once. That is cheap where it is called from (once per voxel in the flood
// fill, which does far more work per voxel) and effectively free in the fragment
// stage, where the only caller is the hand-held light path and runs for the
// frames where something is held up.

#include "/lib/items.glsl"
#include "/lib/blocks.glsl"
#include "/lib/entities.glsl"

'''


def main():
    with open(SETUP, encoding="utf-8") as f:
        lines = f.read().split("\n")

    def find(pat, start=0):
        for i in range(start, len(lines)):
            if re.search(pat, lines[i]):
                return i
        raise SystemExit("could not find %r in setup.csh" % pat)

    # Helpers: the colour constants and the two matrix builders, everything
    # between the first #ifdef IS_LPV_ENABLED's includes and its #endif.
    h0 = find(r"const vec3 LightColor_Amethyst")
    h1 = find(r"^#endif\s*$", h0)
    helpers = lines[h0:h1]

    # The id table: from the local declarations to the end of the last entry.
    t0 = find(r"vec3 lightColor = vec3\(0\.0\);")
    # The last table entry closes just before the saturation block.
    t1 = find(r"// hack to increase light", t0) - 2
    table = lines[t0:t1]

    # Saturation, packing - everything the image store needed except the store.
    p0 = find(r"// hack to increase light")
    p1 = find(r"imageStore\(imgBlockData", p0)
    post = lines[p0:p1]

    if not any("ENTITY_SPECTRAL_ARROW" in l for l in table):
        raise SystemExit("table extraction looks wrong: it does not reach the last entry")
    for l in table + post:
        if "imageStore" in l or "gl_GlobalInvocationID" in l:
            raise SystemExit("compute-only code leaked into the function: %r" % l.strip())

    body = []
    body.append("uvec2 ptBlockLightData(int blockId) {")
    body.append("    // The original returned early for ids past the image width.")
    body.append("    // Nothing indexes the table any more, so the guard is gone; the")
    body.append("    // callers already reject ids they do not have.")
    body.append("")
    body += ["    " + l if l.strip() else "" for l in table]
    body.append("")
    body += ["    " + l if l.strip() else "" for l in post]
    body.append("")
    body.append("    return uvec2(lightColorRange, tintColorMask);")
    body.append("}")
    body.append("")
    body.append("// Unpacks what ptBlockLightData returns, so callers do not each")
    body.append("// repeat the packUnorm4x8 dance.")
    body.append("vec3 ptBlockLightColour(int blockId) {")
    body.append("    return unpackUnorm4x8(ptBlockLightData(blockId).r);")
    body.append("}")
    body.append("")

    text = HEADER + "\n".join(helpers).rstrip() + "\n\n" + "\n".join(body)

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)

    print("wrote %s" % os.path.relpath(OUT, ROOT))
    print("  %d helper lines, %d table lines, %d packing lines"
          % (len(helpers), len(table), len(post)))
    print("  function is %d lines" % text.count("\n"))
    print()
    print("The consumers still read the storage image. Next:")
    print("  lib/diffuse_lighting.glsl   texelFetch(texBlockData, itemId, 0)")
    print("  dimensions/shadowcomp.csh   imageLoad(imgBlockData, int(blockId))")
    print("  4 programs                  uniform usampler1D texBlockData;")
    print("  shaders.properties          image.imgBlockData = ...")
    return 0


if __name__ == "__main__":
    sys.exit(main())
